"""Provider-neutral contracts; core imports no concrete external adapter."""

from datetime import datetime
from decimal import Decimal
from typing import Protocol

from preflight.models import (
    ActorRef,
    AuthContext,
    BillingProjection,
    EventEnvelope,
    EventReceipt,
    FixtureSet,
    Observation,
    ProbeRequest,
    UsageProjection,
)


class FixturePort(Protocol):
    contract_version: str

    def provision(self, run_id: str, requirements: list[str]) -> FixtureSet: ...
    def cleanup(self, run_id: str, fixtures: FixtureSet) -> None: ...


class IdentityTenantPort(Protocol):
    def auth_context(self, actor: ActorRef) -> AuthContext: ...
    def switch_tenant(self, actor_id: str, tenant_id: str) -> AuthContext: ...
    def set_role(self, actor_id: str, tenant_id: str, role: str) -> None: ...
    def remove_membership(self, actor_id: str, tenant_id: str) -> None: ...
    def execute(self, auth: AuthContext, request: ProbeRequest) -> Observation: ...


class BillingStatePort(Protocol):
    def bind_account(self, tenant_id: str, account_id: str) -> None: ...
    def get_binding(self, tenant_id: str) -> str | None: ...
    def create_subscription(
        self, tenant_id: str, plan: str, trial_days: int | None
    ) -> BillingProjection: ...
    def transition(
        self, tenant_id: str, action: str, target_plan: str | None = None
    ) -> BillingProjection: ...
    def projection(self, tenant_id: str) -> BillingProjection: ...
    def entitlements(self, tenant_id: str) -> list[str]: ...


class EventDeliveryPort(Protocol):
    def deliver(self, event: EventEnvelope, auth: AuthContext) -> EventReceipt: ...
    def current_object_version(self, object_id: str) -> int: ...
    def side_effect_count(self, tenant_id: str, counter: str) -> int: ...
    def fail_next_delivery(self, event_type: str) -> None: ...
    def restart(self) -> str: ...


class UsagePort(Protocol):
    def record(
        self, tenant_id: str, meter: str, quantity: Decimal, idempotency_key: str
    ) -> None: ...
    def projection(self, tenant_id: str, meter: str) -> UsageProjection: ...


class ProbeTransport(Protocol):
    name: str
    version: str
    kind: str

    def execute(self, auth: AuthContext, request: ProbeRequest) -> Observation: ...


class ClockPort(Protocol):
    def now(self) -> datetime: ...
    def tick(self, count: int = 1) -> datetime: ...
